# Build Stage
FROM maven:3.8.3-openjdk-17-slim AS build
WORKDIR /app
COPY pom.xml .  
COPY src/ src/  
RUN mvn clean package -DskipTests  

# Runtime Stage
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar  
CMD ["java", "-jar", "app.jar"]
